### ISSUE TITLE
sql/raid-boss-pokedex.sql overwrites column from pokemon-raid-bot.sql

### ISSUE THREAD

**Issue by Fabio1988** [florianbecker/PokemonRaidBot#113]
the SQL script for [raid-boss-pokedex.sql](https://github.com/florianbecker/PokemonRaidBot/blob/master/sql/raid-boss-pokedex.sql) deletes the column "shiny" in table "pokemon", if I executed [pokemon-raid-bot.sql](https://github.com/florianbecker/PokemonRaidBot/blob/master/sql/pokemon-raid-bot.sql) before. I don't think this behaviour is wanted. 

Because when I want to insert the new [gohub-raid-boss-pokedex.sql](https://github.com/florianbecker/PokemonRaidBot/blob/master/sql/gohub-raid-boss-pokedex.sql) (generated with getGOHubDB.php) in the future it's not compatible anymore because of the missing column.

best wishes

**Comment by florianbecker** [comment]
Done with a7ce793
