### ISSUE TITLE
readme.md DOCKER->raidbot installation

### ISSUE THREAD

**Issue by Fabio1988** [florianbecker/PokemonRaidBot#114]
Hello,

https://github.com/florianbecker/PokemonRaidBot#docker

the given shell-code in the topic raidbot installation will clone the "PokemonRaidBot"-repository into the "raidbot-docker" directory.
In your description below, how the directory should look afterwards, the "PokemonRaidBot"-repository is located outside the folder "raidbot-docker".
Should it be located beneath "raidbot-docker" or besides?

Best wishes :)

**Comment by muckelba** [comment]
I just tried it to make sure: If i copy paste the whole code block into my shell, it will create the `raidbot-docker` directory and clone the repository into a new Folder called `PokemonRaidBot` beneath the `raidbot-docker` dir.

**Comment by Fabio1988** [comment]
ah sorry.. I misread it. It was quite difficult to read. It's right in your docu. sorry.

But I still have problems to access to the webhook within the docker. Docker is started and I think the docker is not accessible from outside. but the apache2-default website is accessable.

**Comment by muckelba** [comment]
Feel free to suggest changes to the README or even change it by yourself :) 

The raidbot is exposed at port 8088 by default, but its mandatory to add some sort of SSL proxy to setup the telegram webhook
