### ISSUE TITLE
Raid any time: Change attend time entry

### ISSUE THREAD

**Issue by janhenningsHH** [florianbecker/PokemonRaidBot#148]
When sql_mode is set to "…NO_ZERO_IN_DATE,NO_ZERO_DATE…" the current entry "0000-00-00 00:00:00" is not accepted by the database as a valid date.

When sql_mode cannot be administered by the user, this is a potential problem, because clicking the "raid any time" button doesn't have any effect.

Using "1970-01-01 00:00:00" in vote_time.php would solve the problem of inserting a correct date/time. Other files would have to pick up that change as well, to move from "0000-00-00 00:00:00" to "1970-01-01 00:00:00".

**Comment by Artanicus** [comment]
Leaving some notes here:
- NO_ZERO_IN_DATE,NO_ZERO_DATE is part of the default sql_mode since MySQL 5.7 but not in MariaDB.

**Comment by Artanicus** [comment]
@janhenningsHH Can you try the linked PR and see if it fixes all of the issues for you? In my testing it works but since you have the strict environment to check if anything else breaks. :-)

**Comment by janhenningsHH** [comment]
I'll check and let you know.

**Comment by janhenningsHH** [comment]
Work's like a charm! Thank you!
