### ISSUE TITLE
Missing autorefresh of same raid-posts between several groups

### ISSUE THREAD

**Issue by TommEko** [florianbecker/PokemonRaidBot#154]
Hello,

at the moment there´s no autorefresh for same raid-posts in several groups.  While the raid-overview gets continuously synchronized between the groups by a cronjob, the last editing of a single raid-post does not synchronize with the same post in another group. Both posts run with the same raid ID. Can a cronjob be set up for the autorefresh?

![missingautorefreshred](https://user-images.githubusercontent.com/69113574/90235616-e8d85480-de21-11ea-8652-bbc53a785c41.jpg)

**Comment by Artanicus** [comment]
@TommEko So the bad news is the poll refresh is built exclusively to work with a telegram callback. So calling it any other way right now would not work. To make it work we'd have to build a new function using the cleanup table to locate previously posted still valid raids and trigger a data refresh on them. Not impossible but certainly not fast either.

**Comment by Artanicus** [comment]
Thinking about this more what might make sense is that whenever an update would be triggered, after the main update trigger a check of the cleanup table of other entries for the same raid and also trigger updates for them. That way you don't have to set up another cron job or come up with a timing that works.

**Comment by studplus** [comment]
will be fixed with PR #178

**Comment by Chefkeks** [comment]
Fixed in PR #178
