### ISSUE TITLE
Error 400 - "Bad Request: chat not found" when voting on poll with chat_id larger than 4 bytes.

### ISSUE THREAD

**Issue by AlexxBoo** [florianbecker/PokemonRaidBot#217]
Our group chat has a large chat_id needing more than 4 bytes to be represented as integer in binary.

Example: `"chat_id": 1007481426578` => `11101010 10010010 10010010 10010010 10010010`

Sharing the raid with the group chat works fine. But when voting on a raid poll, the message is not updated. Looking into the issue revealed that the DB attendance table is altered correctly, but the changed raid message can not be updated. The reason seems to be a wrong chat_id, resulting in the "chat not found" error.

Looking into the actual numbers further revealed that the chat_id seems to be truncated to the last 4 bytes during the voting process. This wrong chat_id is than used in the `editMessageCaption` method and results in the error.

Example: `"chat_id": 2459079314` => `10010010 10010010 10010010 10010010`

(chat_id is made up and differs from actual one. It serves to illustrate the issue. Holds true also for negative number representation.)

**Comment by Chefkeks** [comment]
Fixed in PR 218.
