### ISSUE TITLE
@portalmapbot is not working because of reformating

### ISSUE THREAD

**Issue by klablabla** [florianbecker/PokemonRaidBot#273]
The @portalmapbot message has changed it's formating so importal doesn't recognize it.

**Comment by klablabla** [comment]
In the quest bot we had @Ingressportalbot maybe add this aswell.

**Comment by Ninjasoturi** [comment]
@klablabla It is already supported and working

**Comment by klablabla** [comment]
Thanks for the quick reply. 
I didn't get a response after trying. It's added to the database, through /gym I was able to set it visable.
