### ISSUE TITLE
Event name instead of raid boss

### ISSUE THREAD

**Issue by klablabla** [florianbecker/PokemonRaidBot#277]
When we host a event for example community day. The text in the raid bot is Raid Boss.
It would be great if we can we can change this to for example featured pokemon if it is an event.

logic/show_raid_poll.php:78

    `$msg = raid_poll_message($msg, getPublicTranslation('raid_boss') . ': <b>' . get_local_pokemon_name($raid_pokemon_id, $raid['pokemon_form'], true) . '</b>', true);`

**Comment by Ninjasoturi** [comment]
Great suggestion! Is it enough to have only two possible titles (`Raid boss:` and `Featured Pokemon:`) or should it be further customizable?

**Comment by klablabla** [comment]
For now the two should cover 99,9% of the events. 

We used it for Go Fest as well to see who is going. Than you don’t have a featured pokemon or raid boss.
