### ISSUE TITLE
Select multiple raid bosses

### ISSUE THREAD

**Issue by florianbecker** [florianbecker/PokemonRaidBot#3]
If there are more than one raid boss and you are able to choose a raid boss, enable selection of more raid bosses

**Comment by Chefkeks** [comment]
I guess this can be closed :)

**Comment by klablabla** [comment]
@Chefkeks I think not. 
If there are 5 pokemon in an lvl 4 and the player want to do 2 pokemon.

**Comment by Chefkeks** [comment]
Close me! 😁

**Comment by Chefkeks** [comment]
@florianbecker ALREADY DONE! Close this issue ;)
