### ISSUE TITLE
Undefined index: apikey

### ISSUE THREAD

**Issue by Supsuop** [florianbecker/PokemonRaidBot#37]
Hi, 
i have set up your setting with my Google API Key and Telegram Bot Token.
when i send "/start" to the Bot I get just the IP "149.154.167.207" back.
I found this on my logfile:

`PHP Notice:  Undefined index: apikey in /var/www/html/raid.serko.rocks/web/public/core/class/apikey.php on line 17`

Do you have clue why this happens?

**Comment by florianbecker** [comment]
Please join the telegram group: t.me/PokemonBotSupport<http://t.me/PokemonBotSupport>

--
Projektmanager

Florian Becker
Weinberg 60
31134 Hildesheim

Mobil: +49 170 2203719

fb@vxapps.com
https://www.vxapps.com

Am 10.02.2019 um 17:13 schrieb Serhat Saman <notifications@github.com<mailto:notifications@github.com>>:


Hi,
i have set up your setting with my Google API Key and Telegram Bot Token.
when i send "/start" to the Bot I get just the IP "149.154.167.207" back.
I found this on my logfile:

PHP Notice: Undefined index: apikey in /var/www/html/raid.serko.rocks/web/public/core/class/apikey.php on line 17

Do you have clue why this happens?

**Comment by Supsuop** [comment]
Could solve the problem.
I didn't set the apikey by webhook.
I set
https://api.telegram.org/bot111:aaaaaaaa/setWebhook?url=https://xxx.xx/
instead of
https://api.telegram.org/bot111:aaaaaaaa/setWebhook?url=https://xxx.xx/index.php?apikey=111:aaaaaaaa
