### ISSUE TITLE
Exclude GymIDs from Duplicate Check

### ISSUE THREAD

**Issue by quentar82** [florianbecker/PokemonRaidBot#44]
I want still to be able to post "Raid Meeting" as a virtual pokemon on a specific gym. with the new duplicate check it is unable to post further raids on the gym where the "Raid Meeting" also starts.

It would be nice if there will be a setting where you can define one or more gyms which will be excluded from the duplicate check.

**Comment by klablabla** [comment]
@quentar82 You can do it with /list then select the gym and share button.
