### ISSUE TITLE
Exclude reported EX-Raids from duplicate check

### ISSUE THREAD

**Issue by fr3no** [florianbecker/PokemonRaidBot#45]
# Summary
There is no way to post a new raid (e.g. one starting in about an hour) if there has already been reported an EX-Raid starting in a few days.

# Possible fixes
Duplicate check should warn and users should not be able to create a new raid during the same time frame a raid has already been reported. Maybe this is only necessary if there's an Ex-Raid. So Ex-Raids should be excluded from duplicate checks.

**Comment by Chefkeks** [comment]
Once an ex-raid invite is sent out, that gym is kinda locked and there can’t be another raid until the ex-raid took place at that gym - or did I miss something and Niantic changed it?

So technically everything is correct by just checking if there’s still an un-ended (ex-)raid at a gym to avoid duplicates.

**Comment by fr3no** [comment]
As far as I know this has been changed by Niantic. I also looked it up on reddit.

Since we're having an EX-Raid in about one week and I'm gonna report, if there's any other raid hosted at that gym till then.

**Comment by fr3no** [comment]
I can confirm, that we had raids at an EX-Raid gym with a pending invite.

Niantic support confirmed, that gyms with upcoming EX-Raids are no longer locked down:  
https://twitter.com/niantichelp/status/1045735080369549312

**Comment by florianbecker** [comment]
And this Post is from Sept 18! Also they took it back, in case of multiple errors with canceled EX-Raids. So our information currently is: No raids on gyms until the open ex-raid is finished.
