### ISSUE TITLE
Feature Request: Customization option to give the bot access to two channel

### ISSUE THREAD

**Issue by npc015** [florianbecker/PokemonRaidBot#52]
Request: Customization option for the raidbot so that you give the bot access to two channels and it can distinguish between posting the Level 1 to Level 4 raids in one channel and the Level 5 and ex raids in the other channel

**Comment by Chefkeks** [comment]
Included in #53 
For each raid level the SHARE_CHATS can be configured (SHARE_CHATS_LEVEL_5). If there is no SHARE_CHATS_LEVEL_n in the config, the SHARE_CHATS are used.
