### ISSUE TITLE
Change Pokemon via /list troughout to all raid levels

### ISSUE THREAD

**Issue by quentar82** [florianbecker/PokemonRaidBot#54]
When you create a raid egg e.g. Level 4, you can update the pokemon to the specific one after egg is hatched. 

could you implement a function that you can update to every raid level with every pokemon. Use Case is if someone created a level 4 Raid although it is a level 5 Raid you have to delete the whole raid and create it anew. 

with this function you can "update" the raid from a level 4 to a level 5 raid.

**Comment by quentar82** [comment]
can be closed

**Comment by quentar82** [comment]
After Reclarification, reopend. still to analyze to implement function to change pokemon throughout all raid levels via /pokemon

**Comment by Artanicus** [comment]
Tagging as help wanted since it's a fairly niche issue. Ways to avoid this are:
- Limit raid creation to levels that are wanted
- Ingest raids from webhook so that it's not fallible humans creating them.

A PR will be welcome of course.
