### ISSUE TITLE
Empty gym list for gym names with Chinese letters

### ISSUE THREAD

**Issue by AlexxBoo** [florianbecker/PokemonRaidBot#55]
Hi guys, I think my community found a small bug in the RaidBot code.

We have an Arena with the beautiful name '金門大學正門'. Unfortunately it is not selectable anymore. While the first letter shows up in the letter selection message, when pressed however, the actual arena does not show up as a selection.

I assume the issue lies in the function _raid_edit_gym_keys_ in _logic.php_. In line 1057 the SQL query is built with the _$first_length_ variable which itself is derived from the length of the _$first_ letter of the gym name. (line 1032). In our case the Chinese letter '金' yields a _$first_length_ of 3, which in turn breaks the SQL query _... WHERE UPPER(LEFT(gym_name, 3)) ..._.

My workaround for now is to override the _strlen($first)_ statement. If I set _$first_length_ to 1, everything works fine.

**Comment by visiks-vs** [comment]
Hello.

I have same issue with Latvian letters like 'Š'.
My workaround was change strlen to mb_strlen.

strlen('Š') = 2
mb_strlen('Š') = 1

**Comment by Chefkeks** [comment]
As mb_strlen requires additional PHP packages, we will fix it this way:
strlen(utf8_decode('Š')); = 1

**Comment by florianbecker** [comment]
fixed 09c4d1e7250997d1c4db8f806c0d4506f27e653f
