### ISSUE TITLE
Mark Ex-Raid Gyms in Gym-List

### ISSUE THREAD

**Issue by quentar82** [florianbecker/PokemonRaidBot#59]
Implementation of e.g. a Star Emoji in front of all gyms which were ex_gym 1 in gym table. Star Emoji should appear in Rooster where you can chose the gym. 

Pro: Find Ex-Gyms faster.
Cons: None

**Comment by Chefkeks** [comment]
Con: If you just have ex-raid gyms under a certain letter, all gyms would have that star emoji.
Pro: We can of course make that feature configurable: ON/OFF

So will add it when I find the time to do so ;)

**Comment by florianbecker** [comment]
89dad6cbb1f592ce55bd35688c8d58d00f751105
