### ISSUE TITLE
Doc request: Access control example for public groups

### ISSUE THREAD

**Issue by Artanicus** [florianbecker/PokemonRaidBot#62]
Since a public group is identified just by its @handle, would be extremely helpful to have the readme show how this is used in the access files. It's not clear if the @ should be there or not etc.

**Comment by Artanicus** [comment]
After quite some poking I found that even public supergroups have a negative ID but getting it is very difficult since the forward a message to rawdatabot trick doesn't work anymore / with supergroups.
Only way I found was to invite rawdatabot into the supergroup, annoy the hell out of everyone with a jsondump, quickly clean it all up and use that id. Would be much friendlier if there's a way to just use the public handle since apparently that's also a valid id.

**Comment by florianbecker** [comment]
But Ids not changeable. This is a security issue to use the @ token for that.

**Comment by Artanicus** [comment]
https://github.com/florianbecker/PokemonRaidBot/pull/66 includes my attempt at explaining where the IDs can be acquired from.

**Comment by Artanicus** [comment]
#66 was merged so this should be easier now.
