### ISSUE TITLE
Chosing Pokemon as a Raidboss

### ISSUE THREAD

**Issue by quentar82** [florianbecker/PokemonRaidBot#7]
Same Structure as in Gyms with A-Z Rooster like:
A-Z Rooster -> click on A
List of A Pokemon -> click on e.g. Abra
Abra options:
No Raidboss
Tier 1 Boss
Tier 2 Boss
Tier 3 Boss
Tier 4 Boss
Tier 5 Boss
Ex Raid Boss
<Back>

**Comment by Chefkeks** [comment]
Guess this can be closed.
I implemented `/pokedex Mewtwo` or for German `/pokedex Mewtu` and `/pokedex 150`.
It's not A-Z way, but works fast too ;)

**Comment by quentar82** [comment]
will check this when the update is running but seems a nice solution
