### ISSUE TITLE
Importing Gym Picture

### ISSUE THREAD

**Issue by quentar82** [florianbecker/PokemonRaidBot#78]
When Importing a Gym via Importfunction of Portalmapbot the entry in DB created a local folder with the gympicture, instead of the Link to the ingress/google storage where the picture is stored. 

could this be made configurable that user can choose if he want to link a local picture or using the picture of ingress/google storage?!

Thx

**Comment by Chefkeks** [comment]
Will be done, once #79 is merged.

**Comment by quentar82** [comment]
fixed with 1.9.339.5
