### ISSUE TITLE
Add RAID_FIRST_START option

### ISSUE THREAD

**Issue by Chefkeks** [florianbecker/PokemonRaidBot#8]
From our chat:
Question:

> "the range from raid start to first vote button i cant find a setting for"

Answer:

> There is no setting for that yet.
> It depends on you settings.
> We have 15 minute slots here, so:
> a) if a raid egg opens :01 the first option will be :15
> b) if a raid egg opens :00 the first option will be :00 too
> 
> Therefore users here asked if I can add an option if the egg opens at e.g. :01 to raid at :05 since there are still 10 minutes between :05 and :15. But due to the lack of time I'm currently not yet working on it - but that would be the plan to allow the first time (rounded to 5) if it makes sense.
> So for example if the egg opens :06 it doesn't really make sense for me with 15 minute slots to offer :10 and :15 then as voting times.
> 
> This could basically work in the same way the "RAID_LAST_START" works, just for the first start option.

Plan for the feature:
We shall add a RAID_FIRST_START option where you can specify the minimum amount of time in minutes to add an extra voting option like :05 for case a) if that amount of time is given between the raid-start (rounded up to the next 5 minute slot) and the first voting option.

**Comment by florianbecker** [comment]
We need some configuration here.
A) Start at Raidstart
B) Start at 0
C) Start at 5
And a combination of D = B+C and a combination of E = A+B+C

Example:
Raidstart: 10:01
So 05 is near than next 00, so slots will be in 15 Minute Slots:
10:01
10:15
In 10 Minute Slots:
10:01
10:10

But what about 10:01 and 10:11...

I'm not sure, whats the really best option so far - but a start slot, when raid begins seams to be very useful, also nearer slots, but not to much buttons...
