### ISSUE TITLE
Geofence for webhook

### ISSUE THREAD

**Issue by klablabla** [florianbecker/PokemonRaidBot#98]
There is no geofence currently. If a raid from outside the geofence is detected. It will add it to the gym database.
There should also be a check before adding to the database for unknow gym name.

**Comment by florianbecker** [comment]
Update: Do not create a database entry for webhooks, if outside any defined geo locations and check for unknown gym names (but only optionally - maybe gym names not yet pulled, but new gym is important to create poll of)

**Comment by florianbecker** [comment]
Fixed with 8dcfbd5
